services:
  - type: web
    name: png-compressor-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true 